/*
    File: fn_itemWeight.sqf
    Author: Bryan "Tonic" Boardwine

    Description:
    Gets the items weight and returns it.
*/
private["_item"];
_item = [_this,0,"",[""]] call BIS_fnc_param;
if(_item == "") exitWith {};

switch (_item) do
{
    case "oilu": {5};
    case "oilp": {4};
    case "heroinu": {6};
    case "heroinp": {4};
    case "heroinr": {3};
    case "cannabis": {4};
    case "marijuana": {3};
    case "marijuanar": {2};
    case "apple": {1};
    case "peach": {1};
    case "water": {1};
    case "rabbit": {1};
    case "salema": {2};
    case "ornate": {2};
    case "mackerel": {4};
    case "tuna": {6};
    case "mullet": {4};
    case "catshark": {3};
    case "turtle": {3};
    case "fishing": {2};
    case "turtlesoup": {2};
    case "donuts": {1};
    case "coffee": {1};
    case "fuelE": {2};
    case "fuelF": {4};
    case "money": {0};
    case "bluesyn": {3};
    case "pickaxe": {2};
    case "copperore": {4};
    case "ironore": {5};
    case "coalu": {3};
    case "coalp": {3};
    case "steel": {4};
    case "strahler": {2};
    case "barrier": {2};
    case "barricade": {2};
    case "plastic": {4};
    case "hopfen": {2};
    case "malz": {2};
    case "bier": {3};
    case "pilze": {5};
    case "magicmushrooms": {4};
    case "schnaps": {1};
    case "copper_r": {3};
    case "iron_r": {4};
    case "sand": {3};
    case "salt": {3};
    case "salt_r": {2};
    case "glass": {2};
    case "diamond": {5};
    case "diamondc": {4};
    case "cocaine": {6};
    case "cocainep": {4};
    case "spikeStrip": {8};
    case "rock": {5};
    case "schlafmittel": {5};
    case "cement": {4};
    case "goldbar": {10};
    case "blastingcharge": {8};
    case "boltcutter": {3};
    case "defusekit": {2};
    case "Box_IND_WpsSpecial_F": {10};
    case "Box_IND_AmmoVeh_F": {5};
    case "Box_IND_Grenades_F": {7};
    case "B_supplyCrate_F": {15};
    case "zipties": {1};
    case "dattel": {1};
    case "fladenbrot": {1};
    case "ziegenmilch": {1};
    case "burger": {1};
    case "cola": {1};
    case "sprengsatz": {5};
    case "sprengstoff": {10};
    case "fernzuender": {1};
    case "battery": {1};
    case "pipe": {2};
    case "guertel": {2};
    case "antenne": {5};
    case "gehaeuse": {5};
    case "behaelter": {10};
    case "pistolenlieferung": {10};
    case "nahrungsmittel": {10};
    case "munitionslieferung": {15};
    case "aklieferung": {20};
    case "gestohlenevisiere": {15};
    case "uniformen": {15};
    case "koran": {20};
    case "kondome": {25};
    case "sniperkiste": {25};
    case "carbomb1": {5};
    case "carbomb2": {5};
    case "carfernzuender": {2};
    case "golderz": {5};
    case "goldbarren": {3};
    case "depotwaffen": {10};
    case "information": {3};
    case "abhoergeraet": {20};
    case "sulfuru": {3};
    case "sulfurp": {3};
    case "nitre": {3};
    case "potassiumnitrate": {3};
    case "nitroglycerin": {6};
    case "flask": {1};
    case "gunpowder": {6};
    case "explosive": {10};
    case "dogtag": {3};
    case "bandage": {1};
    case "traumakit": {3};
    case "kochsalz": {2};
    default {1};
};
