/*
	Master UI Resource File
*/
#include "common.hpp"
#include "shop_items.hpp"
#include "player_inv.hpp"
#include "gang.hpp"
#include "key_chain.hpp"
#include "impound.hpp"
#include "bank.hpp"
#include "veh_shop.hpp"
#include "shops.hpp"
#include "shops_abzeichen.hpp"
#include "shops_cop.hpp"
#include "shops_cop2.hpp"
#include "shops_level.hpp"
#include "shops_level2.hpp"
#include "shops_level3.hpp"
#include "shops_level4.hpp"
#include "shops_level5.hpp"
#include "shops_level6.hpp"
#include "ui.hpp"
#include "admin_menu.hpp"
#include "cell_phone.hpp"
#include "wanted_list.hpp"
#include "ticket.hpp"
#include "clothing.hpp"
#include "trunk.hpp"
#include "spawnSelection.hpp"
#include "chop_shop.h"
#include "pInteraction.h"
#include "deathScreen.h"
#include "vehicleShop.h"
#include "settings.h"
#include "agb.hpp"
#include "federalReserve.h"
#include "inventar.hpp"
#include "geld.hpp"
//##MarketContent
#include "common_EditorWrapper.hpp"
#include "market.hpp"
#include "craft.hpp"
#include "wantedadd2.hpp"
#include "extended_admin_menu.hpp"
#include "give_money.hpp"
#include "prof.hpp"
#include "schutzgeld.hpp"
#include "giveItem.hpp"
#include "giveItem2.hpp"
#include "reqmedic.hpp"
#include "banking.hpp"

#include "jail_time.hpp"
#include "revoke_license.h"

#include "smartphone.hpp"
#include "channel.hpp"
#include "house_vInv.hpp"
#include "AS_AdminMenu.hpp"
#include "AS_Refund.hpp"
